# Ansible Config
ansible_ssh_private_key_file: /Users/mk/.ssh/ansibleKey

# App Container
container_name: hello
image_name: nginx
# image_name: nginxdemos/hello
host_port: 80
container_port: 80

# EC2
ec2_name: Hello-Ansible
