---

- name: Provision EC2 instance
  ec2_instance:
    key_name: "{{ key_name }}"
    security_group: "{{ security_group_ansible.group_id }}"
    image_id: "{{ image_id }}"
    instance_type: t2.micro
    name: "{{ ec2_name }}"
    tags:
      tool: "{{ ansible_tag }}"
  register: ec2

- name: Add dynamically the newly created EC2 instance to host group Nginx
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: nginx
  with_items: "{{ ec2.instances }}"

- name: Add the newly created EC2 instance to inventory file
  lineinfile:
    dest: "{{ hostpath }}"
    insertafter: "[nginx]"
    line: "{{ item.public_dns_name }}"
    state: present
  with_items: "{{ ec2.instances }}"
